"""Create swap-task Excel files from the validated workbook template."""
from io import BytesIO
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile
import os
import xml.etree.ElementTree as ET


SHEET_XML = {
    "主图数据": "xl/worksheets/sheet1.xml",
    "替换数据": "xl/worksheets/sheet2.xml",
}
FIELDS = ("store_name", "product_id", "image_url", "product_code", "operator", "operator_id")
HEADERS = ("店铺名称", "商品ID", "图片地址", "商品编码", "操作人", "操作人ID")
BODY_STYLES = ("14", "15", "16", "15", "15", "15")
HEADER_STYLES = ("9", "10", "10", "10", "10", "11")
XML_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
NS = {"x": XML_NS}
ET.register_namespace("x", XML_NS)


def _replace_sheet_rows(xml_bytes, records):
    root = ET.fromstring(xml_bytes)
    sheet_data = root.find("x:sheetData", NS)
    if sheet_data is None:
        raise ValueError("Excel template is missing sheetData")

    rows = list(sheet_data.findall("x:row", NS))
    if not rows:
        raise ValueError("Excel template is missing the header row")

    header_row = rows[0]
    for cell in list(header_row.findall("x:c", NS)):
        header_row.remove(cell)
    for column_index, (header, style_id) in enumerate(zip(HEADERS, HEADER_STYLES)):
        column = chr(ord("A") + column_index)
        cell = ET.SubElement(
            header_row,
            f"{{{XML_NS}}}c",
            {"r": f"{column}1", "s": style_id, "t": "inlineStr"},
        )
        inline_string = ET.SubElement(cell, f"{{{XML_NS}}}is")
        ET.SubElement(inline_string, f"{{{XML_NS}}}t").text = header

    columns = root.find("x:cols", NS)
    if columns is not None and not any(
        column.get("min") == "6" for column in columns.findall("x:col", NS)
    ):
        ET.SubElement(
            columns,
            f"{{{XML_NS}}}col",
            {"min": "6", "max": "6", "width": "18", "hidden": "0", "customWidth": "1"},
        )

    for row in rows[1:]:
        sheet_data.remove(row)

    for row_number, record in enumerate(records, start=2):
        row = ET.SubElement(
            sheet_data,
            f"{{{XML_NS}}}row",
            {"r": str(row_number), "ht": "21", "customHeight": "1"},
        )
        for column_index, (field, style_id) in enumerate(zip(FIELDS, BODY_STYLES)):
            column = chr(ord("A") + column_index)
            cell = ET.SubElement(
                row,
                f"{{{XML_NS}}}c",
                {"r": f"{column}{row_number}", "s": style_id, "t": "inlineStr"},
            )
            value = "" if record.get(field) is None else str(record.get(field))
            if value:
                inline_string = ET.SubElement(cell, f"{{{XML_NS}}}is")
                ET.SubElement(inline_string, f"{{{XML_NS}}}t").text = value

    return ET.tostring(root, encoding="utf-8", xml_declaration=True)


def build_swap_workbook(main_rows, replacement_rows, output_path, template_path=None):
    base_dir = Path(__file__).resolve().parent
    template = Path(template_path or base_dir / "assets" / "swap_task_template.xlsx")
    output = Path(output_path)
    if not template.exists():
        raise FileNotFoundError(f"Excel template not found: {template}")

    replacements = {
        SHEET_XML["主图数据"]: list(main_rows),
        SHEET_XML["替换数据"]: list(replacement_rows),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    temp_output = output.with_suffix(output.suffix + ".tmp")

    with ZipFile(template, "r") as source:
        with ZipFile(temp_output, "w", ZIP_DEFLATED) as target:
            for item in source.infolist():
                content = source.read(item.filename)
                if item.filename in replacements:
                    content = _replace_sheet_rows(content, replacements[item.filename])
                target.writestr(item, content)

    os.replace(temp_output, output)
    return str(output)


def _cell_text(cell):
    inline = cell.find("x:is", NS)
    if inline is not None:
        return "".join(node.text or "" for node in inline.findall(".//x:t", NS))
    value = cell.find("x:v", NS)
    return value.text if value is not None and value.text is not None else ""


def read_swap_workbook(workbook_path):
    """Read rows from workbooks generated by build_swap_workbook."""
    result = {}
    with ZipFile(workbook_path, "r") as workbook:
        for sheet_name, sheet_path in SHEET_XML.items():
            root = ET.fromstring(workbook.read(sheet_path))
            sheet_data = root.find("x:sheetData", NS)
            records = []
            if sheet_data is not None:
                for row in sheet_data.findall("x:row", NS)[1:]:
                    values = [""] * len(FIELDS)
                    for cell in row.findall("x:c", NS):
                        reference = cell.get("r", "")
                        if not reference:
                            continue
                        column_index = ord(reference[0].upper()) - ord("A")
                        if 0 <= column_index < len(values):
                            values[column_index] = _cell_text(cell)
                    if any(values):
                        records.append(dict(zip(FIELDS, values)))
            result[sheet_name] = records
    return result
